[package]
name = "tiktok_scraper"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
fantoccini = "0.19"   # WebDriver client
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
